### ISSUE TITLE
Support TigerBeetle v0.15.4 and/or v0.15.5

### ISSUE THREAD

**Issue by jeffutter** [tigerbeetle-rust/tigerbeetle-unofficial#18]
I'm just opening this issue to track any work around these versions.

I started working on `v0.15.4` a week or so ago, bumping versions of the library was easy. There were a couple of build env-related changes, but they were also not too bad. The biggest issue seems like some API changed around network packets IIRC that I got a little tripped up on.

I see now that `v0.15.5` is out now, maybe it'd be more appropriate to ski `v0.15.5`. Anyway, just wanted to open this to see if anyone was working on it so the effort isn't duplicated.

Thanks!

**Comment by jeffutter** [comment]
For anyone looking into this. I’ve got the `-sys` crate building against `0.15.5` in this commit: https://github.com/jeffutter/tigerbeetle-rs/commit/ae8437df5972528ea03fd7be843b3254248d92a5

Still trying to make sense of the changes to the c client api that cause the other crates to break.

**Comment by zetanumbers** [comment]
Can we close this issue after #24 got merged? Or do we specifically need 0.15.5/0.15.4 support too?

**Comment by jeffutter** [comment]
I don't have any specific need for 0.15.5/0.15.4, I'll close this. If anyone does specifically need 0.15.x they'd probably be better off backporting the changes in #24 than working off this.

Thanks.
